
const $=s=>document.querySelector(s), labels={PENDING:'주문대기',PAID:'결제완료',PREPARING:'배송준비',SHIPPED:'배송중',DELIVERED:'배송완료',CONFIRMED:'구매확정',CANCELLED:'취소',REFUND_REQUESTED:'환불요청',REFUNDED:'환불완료'};let status='ALL';
const n=v=>Number(v||0).toFixed(2),dt=v=>v?new Date(v).toLocaleString('ko-KR'):'-';
async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt,headers:{...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false){if(r.status===401)showLogin();throw new Error(d.error||`HTTP ${r.status}`)}return d}
function showLogin(){ $('#loginBox').classList.remove('hidden');$('#panel').classList.add('hidden') } function showPanel(){ $('#loginBox').classList.add('hidden');$('#panel').classList.remove('hidden') }
async function login(){try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:$('#adminKey').value})});$('#adminKey').value='';showPanel();await load();await loadAdminExtras()}catch(e){$('#loginMsg').textContent=e.message}}
async function load(st=status){status=st;try{const [s,o,all]=await Promise.all([api('/api/admin/stats'),api('/api/admin/orders?status='+encodeURIComponent(status)),api('/api/admin/orders?status=ALL')]);showPanel(); const cc=k=>all.orders.filter(x=>x.order_status===k).length; $('#cntPaid').textContent=cc('PAID');$('#cntPrep').textContent=cc('PREPARING');$('#cntShip').textContent=cc('SHIPPED');$('#cntDone').textContent=cc('DELIVERED');$('#stats').innerHTML=[['오늘',s.day_sales],['이번달',s.month_sales],['올해',s.year_sales],['총매출',s.gross_sales],['순매출',s.net_sales]].map(x=>`<div class="stat">${x[0]}<b>${n(x[1])} π</b></div>`).join('');document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.st===status));$('#orders').innerHTML=o.orders.map(card).join('')||'<div class="aorder">해당 주문이 없습니다.</div>'}catch(e){$('#orders').innerHTML=`<div class="aorder">${e.message}</div>`}}
function card(x){const tr=x.tracking_number?`<div class="tracking"><b>배송정보</b><br>택배사: ${x.courier||'-'}<br>송장번호: ${x.tracking_number}</div>`:'';const prep=x.order_status==='PAID'?`<button class="prep" onclick="prep('${x.order_id}')">상품준비</button>`:'';const ship=['PAID','PREPARING'].includes(x.order_status)?`<button class="ship" onclick="ship('${x.order_id}')">배송등록</button>`:'';return `<div class="aorder"><div class="aorder-head"><b>${x.order_id}</b><b>${labels[x.order_status]||x.order_status}</b></div><p>${dt(x.ordered_at)} · ${n(x.paid_total)} π<br>${x.orderer_name||'-'} / ${x.orderer_phone||'-'}<br>받는분: ${x.recipient_name||'-'} / ${x.phone||'-'}<br>${x.postal_code||''} ${x.address||''} ${x.address_detail||''}</p>${tr}<div class="aactions">${prep}${ship}</div></div>`}
async function prep(id){try{await api('/api/admin/orders/'+encodeURIComponent(id)+'/preparing',{method:'POST'});await load()}catch(e){alert(e.message)}}
async function ship(id){const courier=prompt('택배사','CJ대한통운');if(courier===null)return;const trackingNumber=prompt('송장번호');if(!trackingNumber)return;try{await api('/api/admin/orders/'+encodeURIComponent(id)+'/ship',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courier,trackingNumber})});await load()}catch(e){alert(e.message)}}
$('#login').onclick=login;$('#adminKey').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#logout').onclick=async()=>{try{await api('/api/admin/logout',{method:'POST'})}catch{}showLogin()};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>load(b.dataset.st));$('#exportCurrent').onclick=()=>location.href='/api/admin/orders-export.csv?status='+encodeURIComponent(status);$('#exportAll').onclick=()=>location.href='/api/admin/orders-export.csv?status=ALL';
async function loadAdminExtras(){try{const [pr,sr,cr]=await Promise.all([api('/api/admin/products'),fetch('/api/store-settings').then(r=>r.json()),api('/api/admin/categories')]);const st=sr.settings||{};$('#slideYoutube').value=st.slideYoutube||'';$('#shortsUrl').value=st.shortsUrl||'';$('#footerText').value=st.footerText||'';$('#copyright').value=st.copyright||'';$('#terms').value=st.terms||'';$('#privacy').value=st.privacy||'';window._adminProducts=pr.products||[];renderCategories(cr.categories||[]);renderProductAdminList(window._adminProducts);/*`<div class="product-admin-row"><img src="${(p.images||[])[0]||'/images/sample-1.svg'}"><div><b>${p.name}</b><small>${Number(p.price).toFixed(2)} π · ${p.category||''}</small></div><div><button onclick='editProduct(${JSON.stringify(p)})'>수정</button> <button onclick="deleteProduct(${p.id})">삭제</button></div></div>`).join('')*/}catch(e){console.error(e)}}
function renderProductAdminList(list){$('#productAdminList').innerHTML=(list||[]).map(p=>`<div class="product-admin-row"><img src="${(p.images||[])[0]||'/images/sample-1.svg'}"><div><b>${p.name}</b><small>${Number(p.price).toFixed(2)} π · ${p.category||''} · ${p.active!==false?'판매중':'숨김'}</small></div><div><button onclick='editProduct(${JSON.stringify(p)})'>수정</button> <button onclick="deleteProduct(${p.id})">삭제</button></div></div>`).join('')||'<p>검색 결과가 없습니다.</p>'}
function editProduct(p){$('#pid').value=p.id;$('#pname').value=p.name||'';$('#pprice').value=p.price||0;$('#pcategory').value=p.category||'';$('#pshipping').value=p.shipping||0;$('#poptions').value=(p.options||['기본']).join(',');$('#pyoutube').value=p.youtube||'';$('#pimg1').value=(p.images||[])[0]||'';$('#pimg2').value=(p.images||[])[1]||'';$('#pimg3').value=(p.images||[])[2]||'';$('#psort').value=p.sortOrder||p.id;$('#pdesc').value=p.detail||p.desc||'';$('#pactive').checked=p.active!==false;window.scrollTo({top:0,behavior:'smooth'})}
function clearProduct(){['pid','pname','pprice','pyoutube','pimg1','pimg2','pimg3','pdesc'].forEach(x=>$('#'+x).value='');$('#pcategory').value='생활';$('#pshipping').value=0;$('#poptions').value='기본';$('#psort').value=1;$('#pactive').checked=true}
async function saveProduct(){const imgs=[$('#pimg1').value,$('#pimg2').value,$('#pimg3').value].map(x=>x.trim()).filter(Boolean);const body={id:Number($('#pid').value)||undefined,name:$('#pname').value.trim(),price:Number($('#pprice').value)||0,category:$('#pcategory').value.trim(),shipping:Number($('#pshipping').value)||0,shippingText:Number($('#pshipping').value)?`${$('#pshipping').value} π`:'무료배송',options:$('#poptions').value.split(',').map(x=>x.trim()).filter(Boolean),youtube:$('#pyoutube').value.trim(),images:imgs,desc:$('#pdesc').value.trim(),detail:$('#pdesc').value.trim(),active:$('#pactive').checked,sortOrder:Number($('#psort').value)||1};if(!body.name)return alert('상품명을 입력하세요.');await api('/api/admin/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});clearProduct();await loadAdminExtras();alert('상품을 저장했습니다.')}
async function deleteProduct(id){const info=await api('/api/admin/products/'+id+'/delete-check');const msg=info.orderCount>0?`이 상품은 주문내역 ${info.orderCount}건에 포함되어 있습니다.\n삭제해도 주문 당시 상품명/가격은 유지되지만 상품 이미지 연결은 없어질 수 있습니다.\n\n그래도 삭제할까요?`:'이 상품을 삭제할까요?';if(!confirm(msg))return;await api('/api/admin/products/'+id,{method:'DELETE'});await loadAdminExtras()}
$('#saveProduct').onclick=()=>saveProduct().catch(e=>alert(e.message));$('#clearProduct').onclick=clearProduct;$('#seedProducts').onclick=async()=>{await api('/api/admin/seed-products',{method:'POST'});await loadAdminExtras();alert('샘플 상품을 등록했습니다.')};$('#saveStore').onclick=async()=>{await api('/api/admin/store-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slideYoutube:$('#slideYoutube').value.trim(),shortsUrl:$('#shortsUrl').value.trim()})});alert('저장했습니다.')};$('#saveBasic').onclick=async()=>{await api('/api/admin/store-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({footerText:$('#footerText').value,copyright:$('#copyright').value,terms:$('#terms').value,privacy:$('#privacy').value})});alert('상점 기본정보를 저장했습니다.')};$('#toggleCategories').onclick=()=>$('#categoryManageBody').classList.toggle('hidden');$('#productSearchBtn').onclick=()=>{const q=$('#productSearch').value.trim().toLowerCase();renderProductAdminList((window._adminProducts||[]).filter(p=>!q||(p.name||'').toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q)))};$('#productSearch').addEventListener('input',()=>$('#productSearchBtn').click());

function showAdminTab(name){document.querySelectorAll('.admin-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.admin-section').forEach(x=>x.classList.toggle('hidden',x.dataset.section!==name));}
document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>showAdminTab(b.dataset.tab));
function renderCategories(cs){const box=$('#categoryList');if(!box)return;box.innerHTML=cs.map(c=>`<div class="category-row"><input value="${c.name}" data-old="${c.name}" class="cat-name"><input type="number" value="${c.sort_order||0}" class="cat-sort"><label><input type="checkbox" class="cat-active" ${c.active?'checked':''}> 노출</label><button onclick="saveCategoryRow(this)">저장</button><button onclick="deleteCategory('${encodeURIComponent(c.name)}')">삭제</button></div>`).join('');}
async function saveCategoryRow(btn){const r=btn.closest('.category-row'),body={oldName:r.querySelector('.cat-name').dataset.old,name:r.querySelector('.cat-name').value.trim(),sortOrder:Number(r.querySelector('.cat-sort').value)||0,active:r.querySelector('.cat-active').checked};await api('/api/admin/categories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await loadAdminExtras();}
async function addCategory(){const name=$('#newCategory').value.trim();if(!name)return;await api('/api/admin/categories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,active:true,sortOrder:99})});$('#newCategory').value='';await loadAdminExtras();}
async function deleteCategory(name){if(!confirm('카테고리를 삭제할까요? 등록 상품이 있으면 삭제되지 않습니다.'))return;try{await api('/api/admin/categories/'+name,{method:'DELETE'});await loadAdminExtras()}catch(e){alert(e.message)}}
(async()=>{try{await api('/api/admin/session');showPanel();await load();await loadAdminExtras()}catch{showLogin()}})();
